# Copyright (C) 2017-2018 The MoKee Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sharp/LA29/setup-makefiles.sh

#DRM
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/sharp/LA29/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/sharp/LA29/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/sharp/LA29/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

# Graphics
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/libq3dtools_esx.so:system/vendor/lib64/egl/libq3dtools_esx.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    vendor/sharp/LA29/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/sharp/LA29/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/sharp/LA29/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/sharp/LA29/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw

# Media
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so

# Media firmware
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/sharp/LA29/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Perf
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/bin/energy-awareness:system/bin/energy-awareness \
    vendor/sharp/LA29/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    vendor/sharp/LA29/proprietary/bin/perfd:system/bin/perfd \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so

# Peripheral manager
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/bin/pm-proxy:system/bin/pm-proxy \
    vendor/sharp/LA29/proprietary/bin/pm-service:system/bin/pm-service \
    vendor/sharp/LA29/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so

# Postprocessing
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so

# Radio
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sharp/LA29/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sharp/LA29/proprietary/bin/radish:system/bin/radish \
    vendor/sharp/LA29/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/sharp/LA29/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/sharp/LA29/proprietary/lib64/libcnefeatureconfig.so:system/lib64/libcnefeatureconfig.so \
    vendor/sharp/LA29/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/sharp/LA29/proprietary/lib64/librmnetctl.so:system/lib64/librmnetctl.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so

# QMI
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so

# Thermal
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/sharp/LA29/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so

# DPM
PRODUCT_COPY_FILES += \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdpmctmgr.so:system/vendor/lib64/libdpmctmgr.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdpmfdmgr.so:system/vendor/lib64/libdpmfdmgr.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdpmframework.so:system/vendor/lib64/libdpmframework.so \
    vendor/sharp/LA29/proprietary/vendor/lib64/libdpmnsrm.so:system/vendor/lib64/libdpmnsrm.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    vendor/sharp/LA29/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so

PRODUCT_PACKAGES += \
    TimeService \
    libFlacSwDec \
    libmdmdetect \
    libTimeService \
    com.qualcomm.location \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook \
    libtime_genoff
